# Generated by Django 4.2.29 on 2026-04-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='retrieved_chunks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
