# Generated by Django 4.2.29 on 2026-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_retrieved_chunks_message_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tokens',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
